---
- hosts: 172.31.0.190
  become: yes
  tasks:
  - name: I want to execute linu command
    command: hostname -f
    register: myResult
  - name: I want to display first task myResult
    debug:
      msg: "{{myResult}}"