---
- hosts: 172.31.0.190
  become: yes
  tasks:
  - name: I want to execute linu command
    command: hostname -f
    register: myResult
  - name: I want to display first task myResult
    debug:
      msg: "{{myResult}}"
  # Based on above result i want to execute the below flow 
  - name: install git
    yum:
      name: git
      state: present
    when: myResult.stdout != ""
  - name: install tree
    yum:
      name: tree
      state: present
    when: myResult.stdout == ""