---
- hosts: all
  become: yes
  tasks:
  - name: install git
    yum:
      name: git
      state: present
  - name: install tree
    yum:
      name: tree
      state: present
  - name: install wget
    yum:
      name: wget
      state: present
  - name: install webserver
    yum:
      name: httpd
      state: latest
  # - name: stop webserver
  #   service:
  #     name: httpd
  #     state: stopped
