---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install git
    yum:
      name: "{{myGitPackOnRedhat}}"
      state: present
  - name: install tree
    yum:
      name: "{{myTreePackOnRedhat}}"
      state: present
  - name: install wget
    yum:
      name: "{{myWgetPackOnRedhat}}"
      state: present
  - name: install webserver
    yum:
      name: "{{myWebPackOnRedhat}}"
      state: latest
  - name: stop webserver
    service:
      name: "{{myWebPackOnRedhat}}"
      state: stopped
  - name: restart webserver
    service:
      name: "{{myWebPackOnRedhat}}"
      state: restarted
  - name: reload webserver
    service:
      name: "{{myWebPackOnRedhat}}"
      state: reloaded
  - name: Install java
    yum:
      name: "{{myJavaPackOnRedhat}}"
      state: present
