---
- hosts: 172.31.0.190
  become: yes
  tasks:
  - name: I want to create folder
    file: 
      path: /home/sirimalli/myFolder
      state: directory

  - include_tasks: myFile.yml 

  - name: copy the file into node side
    copy: 
      src: myTestFile
      dest: /home/sirimalli/myFolder
