---
- hosts: 172.31.0.190
  become: yes
  tasks:
  - name: I want to create folder
    file: 
      path: /home/sirimalli/myFolder
      state: directory

  - include_tasks: myFile.yml 

  - name: copy the file into node side
    copy: 
      src: myTestFile
      dest: /home/sirimalli/myFolder

  - name: I want to donwload internet file
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0.tar.gz
      dest: /home/sirimalli/myFolder/apache-tomcat-10.0.0.tar.gz
      force_basic_auth: yes
  

  # Using handlers we can resuse the tak for several tasks


  - name: install webserver
    yum:
      name: httpd
      state: latest
    notify: restart webserver

  handlers:
  - name: restart webserver
    service:
      name: httpd
      state: restarted
  
